### ISSUE TITLE
Inquiry About the Next NPM Package Release

### ISSUE THREAD

**Issue by otkHsiao** [microsoft/eslint-plugin-fluentui-jsx-a11y#134]
Hi  @aubreyquinn 

First of all, thank you for your amazing work on this project! I recently noticed that the latest updates in the GitHub repository include a fix for [hasNonEmptyProp](https://github.com/microsoft/eslint-plugin-fluentui-jsx-a11y/blob/65163aab24447003227a3c04aba8db219062eaf1/lib/util/hasNonEmptyProp.ts#L14)

I wanted to check if there are any plans to publish a new version of the package on NPM soon, as this update would be incredibly helpful for my project.

Thank you in advance for your time and effort, and I appreciate any insights you can provide!

Best regards

**Comment by aubreyquinn** [comment]
Thank you, @otkHsiao ! I can do this later on today :)

**Comment by aubreyquinn** [comment]
Hi @otkHsiao , it should be available now. 3.0.0-alpha.2
