### ISSUE TITLE
MenuItem needs an accessible name

### ISSUE THREAD

**Issue by aubreyquinn** [microsoft/eslint-plugin-fluentui-jsx-a11y#43]
Write an ESLint rule ensuring that the MenuItem component has an accessible name.          <MenuItem
            icon={<CutIcon />}
            onClick={() => alert("Cut to clipboard")}
          >

**Comment by nikitasingla-MSFT** [comment]
PR [here](https://github.com/microsoft/eslint-plugin-fluentui-jsx-a11y/pull/57/)
