### ISSUE TITLE
ToggleButton needs an accessible name

### ISSUE THREAD

**Issue by aubreyquinn** [microsoft/eslint-plugin-fluentui-jsx-a11y#44]
<Tooltip content="With calendar icon only" relationship="label">
        <ToggleButton
          checked={checked3}
          icon={checked3 ? <CalendarMonth /> : <CalendarMonthRegular />}
          onClick={() => toggleChecked(3)}
        />
      </Tooltip>

**Comment by samr874** [comment]
> ```
>   <Tooltip content="With calendar icon only" relationship="label">
>     <ToggleButton
>       checked={checked3}
>       icon={checked3 ? <CalendarMonth /> : <CalendarMonthRegular />}
>       onClick={() => toggleChecked(3)}
>     />
>   </Tooltip>
> ```

I want to work on this issue please assign it to me

**Comment by aubreyquinn** [comment]
Hi @samr874 , I think the code has already been merged.

**Comment by nikitasingla-MSFT** [comment]
PR [here](https://github.com/microsoft/eslint-plugin-fluentui-jsx-a11y/pull/63)

**Comment by nikitasingla-MSFT** [comment]
Closing this item, PR [here](https://github.com/microsoft/eslint-plugin-fluentui-jsx-a11y/pull/63)
