### ISSUE TITLE
create a warning to suggesting that a visual label is better than an aria-label

### ISSUE THREAD

**Issue by aubreyquinn** [microsoft/eslint-plugin-fluentui-jsx-a11y#59]
e.g Dropdown component, SpinButton component or certain buttons

**Comment by aubreyquinn** [comment]
Hi @shweta786 , this article gives a good explanation of the rule: 
https://react.fluentui.dev/?path=/docs/components-searchbox--docs#placeholder

Basically, aria-label is going to give screen reader users access to the information but that's not great for sighted users :)

**Comment by shweta786** [comment]
raised PR https://github.com/microsoft/eslint-plugin-fluentui-jsx-a11y/pull/114
