### ISSUE TITLE
create a rule for no empty buttons

### ISSUE THREAD

**Issue by aubreyquinn** [microsoft/eslint-plugin-fluentui-jsx-a11y#68]
Empty buttons pose an accessibility issue for sighted users. To be accessible to sighted users, a button must either contain an image or text content.

**Comment by nikitasingla-MSFT** [comment]
PR [here](https://github.com/microsoft/eslint-plugin-fluentui-jsx-a11y/pull/63)

**Comment by nikitasingla-MSFT** [comment]
PR [here](https://github.com/microsoft/eslint-plugin-fluentui-jsx-a11y/pull/63)
