### ISSUE TITLE
update coverage.md file

### ISSUE THREAD

**Issue by aubreyquinn** [microsoft/eslint-plugin-fluentui-jsx-a11y#84]
Since our last hackathon, the Fluent team has added more components so we need to update the coverage.md file with the new components.

**Comment by Harsh-Modi278** [comment]
Can you please assign it to me? 

I want to take up this task for warmup PR. I plan to refer https://react.fluentui.dev/ for adding new components.

**Comment by aubreyquinn** [comment]
[like]  Aubrey Quinn reacted to your message:
________________________________
