### ISSUE TITLE
investigate how to migrate the repo from ES5 to Typescript

### ISSUE THREAD

**Issue by aubreyquinn** [microsoft/eslint-plugin-fluentui-jsx-a11y#86]
investigate how to migrate the repo from ES5 to Typescript

**Comment by ajayagr** [comment]
Migration plan from ES5 to TS:
- Install TypeScript and Type Definitions
- Create and configure tsconfig.json file
- Port existing JS rules to use the new typescript packages and add type annotations wherever required.
- Port existing test to use the new typescript packages
- Check and update package.json file to ensure dependencies are managed properly.

**Comment by aubreyquinn** [comment]
[like]  Aubrey Quinn reacted to your message:
________________________________
